# Use root/example as user/password credentials
version: '3.9'

services:
  node:
    build: ./
    command: "node ./build/server.js"
    restart: always
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      SALT_ROUNDS: 12
      JWT_SECRET_ACCESS: some_random_string
      JWT_SECRET_REFRESH: some_random_string_2
      MONGODB_URL: mongodb://root:example@mongo:27017
    ports:
      - 5000:5000
    networks:
      - net

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27050:27017
    networks:
      - net
    volumes:
      - ./.database/mongo:/data/db

networks:
  net:
    driver: bridge
